### ISSUE TITLE
Features.h no such file

### ISSUE THREAD

**Issue by shannon** [t2age/webrtcarmv6#1]
I came across this repo from https://github.com/node-webrtc/node-webrtc/issues/558.

I tried to follow the instructions but I can't seem to get past the following error during the npm install step:

```
In file included from /usr/local/src/node-webrtc/build/external/libwebrtc/download/src/buildtools/third_party/libc++/trunk/include/stddef.h:39:0,
                 from /usr/local/src/node-webrtc/build/node/v13.7.0/include/js_native_api.h:5,
                 from /usr/local/src/node-webrtc/build/node/v13.7.0/include/node_api.h:10,
                 from /usr/local/src/node-webrtc/node_modules/node-addon-api/napi.h:4,
                 from /usr/local/src/node-webrtc/src/binding.cc:8:
/usr/local/src/node-webrtc/build/external/libwebrtc/download/src/buildtools/third_party/libc++/trunk/include/__config:215:24: fatal error: features.h: No such file or directory
 #  include <features.h>
                        ^
compilation terminated.
```

The only thing I could find online was possibly a missing libc-dev package but I've checked and that is definitely installed and features.h is present. This was part of the installed packages with the depot_tools install-build-deps.sh.

```
root@53013c57fc4d:/usr/local/src/node-webrtc# ls /usr/include/features.h -l 
-rw-r--r-- 1 root root 15541 Apr 16  2018 /usr/include/features.h
```

I was just wondering if you came across this issue when you were writing this tutorial and if you have any suggestions for where to look.

**Comment by t2age** [comment]
Hi.
I DO NOT remember to have had such error...

I did use Ubuntu 18.04 Desktop as dev machine.
All other steps used was documented on the instructions...

Regards,
Valter

**Comment by shannon** [comment]
Thanks @t2age. I figured it out. I had the wrong sysroot in my cmakelist. It wasn't obvious what was wrong because it worked up to that point. 

I have a build running on my pi zero now. Thanks for this tutorial.
